name: softechapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.1
  lottie: 
  loading_indicator: ^3.1.1
  persistent_bottom_nav_bar: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.18.1
  http: ^1.1.0
  table_calendar: ^3.0.9
  calendar_day_view: 
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Jost
      fonts:
        - asset: lib/fonts/Jost/static/Jost-Bold.ttf
          weight: 700
        - asset: lib/fonts/Jost/static/Jost-Regular.ttf
          weight: 400
        - asset: lib/fonts/Jost/static/Jost-Light.ttf
          weight: 300
        - asset: lib/fonts/Jost/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Jost/static/Jost-Medium.ttf
          weight: 500
        - asset: lib/fonts/Jost/static/Jost-SemiBold.ttf
          weight: 600