// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDSt_doO7mWTVTIDsI5o7GFxZ0IzEAag',
    appId: '1:766993715782:web:a6818b516f898033f0b047',
    messagingSenderId: '766993715782',
    projectId: 'softtechapp-1ac9a',
    authDomain: 'softtechapp-1ac9a.firebaseapp.com',
    storageBucket: 'softtechapp-1ac9a.firebasestorage.app',
    measurementId: 'G-ZMHXXRQ694',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuSVG5oT46Jj1OYS7e35dNEgPTMbS1Neo',
    appId: '1:766993715782:android:e966b1b999417a4af0b047',
    messagingSenderId: '766993715782',
    projectId: 'softtechapp-1ac9a',
    storageBucket: 'softtechapp-1ac9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2HrDff1_qSwMZ9o1t01opqrPX8M44r48',
    appId: '1:766993715782:ios:91f86f1e1d1c31baf0b047',
    messagingSenderId: '766993715782',
    projectId: 'softtechapp-1ac9a',
    storageBucket: 'softtechapp-1ac9a.firebasestorage.app',
    iosBundleId: 'com.example.softechapp',
  );
}
